#.codeclimate.yml
version: "2"

engines:
  duplication:
    enabled: false
    config:
      languages: -javascript
  eslint:
    enabled: true
    checks:
      similar-code:
        enabled: false
      method-lines: 
        config:
          threshold: 50

exclude_patterns:
  - "tests/"
  - "node_modules/"
  - ".nyc_output"
  - "coverage"
  - "./specs/*.js"
